version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ml_app
      POSTGRES_USER: ml_app_user
      POSTGRES_PASSWORD: ml_app_password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./app/
    env_file:
      - ./app/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data:
    driver: local
